INSERT INTO artist(`index`, artist, genre)
     VALUES (0, '_ & The Mysterians', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (1, '18 South', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (2, 'A Fielder Boston Pops', 'Classic');INSERT INTO artist(`index`, artist, genre)
     VALUES (3, 'ADELE', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (4, 'Aerosmith', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (5, 'Al DiMeola', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (6, 'Alabama', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (7, 'Alex Hargreaves', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (8, 'Alexander', 'Pop');INSERT INTO artist(`index`, artist, genre)
        VALUES (
                  9,
                  'Alfred Hause And His Vienna Waltz Country Ballroom Orchestra',
                  'Classic');INSERT INTO artist(`index`, artist, genre)
     VALUES (10, 'Alice Cooper', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (11, 'Alison Krauss', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (12, 'Alison Krauss & Union Station', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (13, 'Aloe Blacc', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (14, 'Alvin Lee', 'Blues');INSERT INTO artist(`index`, artist, genre)
     VALUES (15, 'Alvin Lee & Ten Years Later', 'Blues');INSERT INTO artist(`index`, artist, genre)
     VALUES (16, 'America', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (17, 'Andre Kostelanetz and his orchestra', 'Classic');INSERT INTO artist(`index`, artist, genre)
     VALUES (18, 'Tim O''Brien', 'BlueGrass');INSERT INTO artist(`index`, artist, genre)
     VALUES (19, 'Angèle Dubeau & La Pietà', 'Classic');INSERT INTO artist(`index`, artist, genre)
     VALUES (20, 'Antonio Vivaldi', 'Classic');INSERT INTO artist(`index`, artist, genre)
     VALUES (21, 'Antony & The Johnsons', 'Folk');INSERT INTO artist(`index`, artist, genre)
     VALUES (22, 'Arcade Fire', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (23, 'Aretha Franklin', 'Soul');INSERT INTO artist(`index`, artist, genre)
     VALUES (24, 'Arlo Guthrie', 'Folk');INSERT INTO artist(`index`, artist, genre)
     VALUES (25, 'Armik', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (26, 'Asleep At the Wheel', 'TexMex');INSERT INTO artist(`index`, artist, genre)
     VALUES (27, 'Assassin', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (28, 'Average White Band', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (29, 'Bachman-Turner Overdrive', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (30, 'Bad Company', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (31, 'Badfinger', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (32, 'Barry McGuire', 'Folk');INSERT INTO artist(`index`, artist, genre)
     VALUES (33, 'Beady Eye', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (34, 'Beatles', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (35, 'Bee Gees', 'Folk');INSERT INTO artist(`index`, artist, genre)
     VALUES (36, 'Ben E. King', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (37, 'Ben Harper', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (38, 'Benedetti & Svoboda', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (39, 'Big Brother & the Holding Company_Janis Joplin', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (40, 'Bill Haley & His Comets', 'RockaBilly');INSERT INTO artist(`index`, artist, genre)
     VALUES (41, 'Bill Perry', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (42, 'Bill Withers', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (43, 'Billy Holliday', 'Jazz');INSERT INTO artist(`index`, artist, genre)
     VALUES (44, 'Billy Joel', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (45, 'Billy Lee Riley', 'RockaBilly');INSERT INTO artist(`index`, artist, genre)
     VALUES (46, 'Bing Crosby', 'Holiday');INSERT INTO artist(`index`, artist, genre)
     VALUES (47, 'Blood Sweat & Tears', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (48, 'Blue Swede', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (49, 'Blues Image', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (50, 'Bob Dylan', 'Folk');INSERT INTO artist(`index`, artist, genre)
     VALUES (51, 'Bob Dylan & The Band', 'Folk');INSERT INTO artist(`index`, artist, genre)
     VALUES (52, 'Bob Forrest', 'Folk');INSERT INTO artist(`index`, artist, genre)
     VALUES (53, 'Bob Marley', 'Regae');INSERT INTO artist(`index`, artist, genre)
     VALUES (54, 'Bob Marley & The Wailers', 'Regae');INSERT INTO artist(`index`, artist, genre)
     VALUES (55, 'Bob Seger', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (56, 'Bobby Darin', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (57, 'Bobby Rydell', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (58, 'Bon Jovi', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (59, 'Booker T. & The MG''s', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (60, 'Booker T. Jones', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (61, 'Boston', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (62, 'Boxcar Willie', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (63, 'Boz Scaggs', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (64, 'Branford Marsalis', 'Jazz');INSERT INTO artist(`index`, artist, genre)
     VALUES (65, 'Branford Marsalis & Orpheus Chamber Orchestra', 'Jazz');INSERT INTO artist(`index`, artist, genre)
     VALUES (66, 'Brecker Bothers', 'Jazz');INSERT INTO artist(`index`, artist, genre)
     VALUES (67, 'Brecker Bothers Band', 'Jazz');INSERT INTO artist(`index`, artist, genre)
     VALUES (68, 'Brecker Brothers', 'Jazz');INSERT INTO artist(`index`, artist, genre)
     VALUES (69, 'Brecker Brothers Band', 'Jazz');INSERT INTO artist(`index`, artist, genre)
     VALUES (70, 'Brenda Lee', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (71, 'Brewer & Shipley', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (72, 'Bruce Springsteen', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (73, 'Buddy Holly', 'RockaBilly');INSERT INTO artist(`index`, artist, genre)
     VALUES (74, 'Buddy Tate', 'Jazz');INSERT INTO artist(`index`, artist, genre)
     VALUES (75, 'Buffalo Springfield', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (76, 'Calexico & Charlotte Gainsbourg', 'Folk');INSERT INTO artist(`index`, artist, genre)
     VALUES (77, 'Canned Heat', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (78, 'Carl Perkins', 'RockaBilly');INSERT INTO artist(`index`, artist, genre)
     VALUES (79, 'Carole King', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (80, 'Cat Power', 'Folk');INSERT INTO artist(`index`, artist, genre)
     VALUES (81, 'Cat Stevens', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (82, 'Celtic Christmas', 'Holiday');INSERT INTO artist(`index`, artist, genre)
     VALUES (83, 'Chad & Jeremy', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (84, 'Chanel Campbell', 'Country');INSERT INTO artist(`index`, artist, genre)
        VALUES (
                  85,
                  'Charles Dutoit, Kyung Wha Chung & Philharmonia Orchestra',
                  'Classic');INSERT INTO artist(`index`, artist, genre)
     VALUES (86, 'Charlie Daniels Band', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (87, 'Charlie Rich', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (88, 'Cheap Trick', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (89, 'Chet Atkins and Hank Snow', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (90, 'Chicago', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (91, 'Chick Corea', 'Jazz');INSERT INTO artist(`index`, artist, genre)
     VALUES (92, 'Chuck Berry', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (93, 'Chuscales', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (94, 'Citizen Cope', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (95, 'City and Colour', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (96, 'Clarence Gatermouth Brown', 'Blues');INSERT INTO artist(`index`, artist, genre)
     VALUES (97, 'Classics IV', 'Classic');INSERT INTO artist(`index`, artist, genre)
     VALUES (98, 'Cody Bryant and The Riders Of The Purple Sage', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (99, 'Cold War Kids', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (100, 'Colt Ford', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (101, 'Commander Cody & His Lost Planet Airmen', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (102, 'Cream', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (103, 'Creedence Clearwater Revival', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (104, 'Crooked Still', 'BlueGrass');INSERT INTO artist(`index`, artist, genre)
     VALUES (105, 'Crosby, Stills, Nash & Young', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (106, 'Dale Hawkins', 'RockaBilly');INSERT INTO artist(`index`, artist, genre)
     VALUES (107, 'Darius Brubeck', 'Jazz');INSERT INTO artist(`index`, artist, genre)
     VALUES (108, 'Dave Brubeck', 'Jazz');INSERT INTO artist(`index`, artist, genre)
     VALUES (109, 'Dave Brubeck Quartet', 'Jazz');INSERT INTO artist(`index`, artist, genre)
     VALUES (110, 'Dave Edmunds', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (111, 'Dave Mason', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (112, 'David Allan Coe', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (113, 'David Bowie', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (114, 'David Bromberg Band', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (115, 'Death Cab for Cutie', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (116, 'Deep Purple', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (117, 'Del Shannon', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (118, 'Della Mae', 'BlueGrass');INSERT INTO artist(`index`, artist, genre)
     VALUES (119, 'Derek & The Dominos', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (120, 'Desmond Dekker', 'Regae');INSERT INTO artist(`index`, artist, genre)
     VALUES (121, 'Devin Duval', 'Jazz');INSERT INTO artist(`index`, artist, genre)
     VALUES (122, 'Diego Garcia', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (123, 'Dierks Bentley', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (124, 'Dire Straits', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (125, 'Dixie Chicks', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (126, 'Dolly Parton', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (127, 'Don McLean', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (128, 'Donovan', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (129, 'Doobie Brothers', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (130, 'Dr. John', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (131, 'Dropkick Murphys', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (132, 'Duke Ellington', 'Jazz');INSERT INTO artist(`index`, artist, genre)
     VALUES (133, 'Dvorak', 'Classic');INSERT INTO artist(`index`, artist, genre)
     VALUES (134, 'Eddie Vedder', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (135, 'Eddie Vedder & The Million Dollar Bashers', 'Folk');INSERT INTO artist(`index`, artist, genre)
     VALUES (136, 'Eilen Jewell', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (137, 'Eldorado', 'TexMex');INSERT INTO artist(`index`, artist, genre)
     VALUES (138, 'Electric Light Orchestra', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (139, 'Elton John', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (140, 'Elvis Presley', 'Holiday');INSERT INTO artist(`index`, artist, genre)
     VALUES (141, 'Emmylou Harris', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (142, 'Eric Burdon & The Animals', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (143, 'Eric Clapton', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (144, 'Eric Clapton & B.B. King', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (145, 'Eric Clapton, Jeff Beck & The Yardbirds', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (146, 'Fleet Foxes', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (147, 'Fleetwood Mac', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (148, 'Foghat', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (149, 'Foy Willing & The Riders Of The Purple Sage', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (150, 'Francesco de Gregori', 'Folk');INSERT INTO artist(`index`, artist, genre)
     VALUES (151, 'Frank Sinatra', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (152, 'Freddie Notes & The Rudies', 'Regae');INSERT INTO artist(`index`, artist, genre)
     VALUES (153, 'Freddy Fender', 'TexMex');INSERT INTO artist(`index`, artist, genre)
        VALUES (
                  154,
                  'Gary Burton, Steve Swallow, Roy Haynes, Tiger Okoshi',
                  'Jazz');INSERT INTO artist(`index`, artist, genre)
     VALUES (155, 'Gary Lewis & The Playboys', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (156, 'Gary Puckett & The Union Gap', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (157, 'Generationals', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (158, 'George Harrison', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (159, 'Gerry Rafferty', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (160, 'Gillian Welch', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (161, 'Glasser', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (162, 'Glen Campbell & Rita Coolidge', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (163, 'Glen Hansard & Markéta Irglová', 'Folk');INSERT INTO artist(`index`, artist, genre)
     VALUES (164, 'Golden Earring', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (165, 'Gordon Lightfoot', 'Folk');INSERT INTO artist(`index`, artist, genre)
     VALUES (166, 'Grand Funk Railroad', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (167, 'Gregg Allman', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (168, 'Guns N'' Roses', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (169, 'Hair', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (170, 'Hair Musical', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (171, 'Hank Williams', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (172, 'Hank Williams, Jr_', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (173, 'Harry Belafonte', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (174, 'Harry Nilsson', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (175, 'Heart', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (176, 'Herbie Hancock', 'Jazz');INSERT INTO artist(`index`, artist, genre)
     VALUES (177, 'Hot Tuna', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (178, 'Howard Shore', 'Folk');INSERT INTO artist(`index`, artist, genre)
     VALUES (179, 'Humble Pie', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (180, 'Ike and Tina Turner', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (181, 'Infamous Stringdusters', 'BlueGrass');INSERT INTO artist(`index`, artist, genre)
     VALUES (182, 'Iron & Wine', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (183, 'Iron & Wine With Calexico', 'Folk');INSERT INTO artist(`index`, artist, genre)
     VALUES (184, 'Iron Butterfly', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (185, 'Iron Butterfly & Vanilla Fudge', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (186, 'Jack Ingram', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (187, 'Jack Johnson', 'Folk');INSERT INTO artist(`index`, artist, genre)
     VALUES (188, 'Jackson Browne', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (189, 'James Gang', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (190, 'James Otto', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (191, 'Jamey Johnson', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (192, 'Jan & Dean', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (193, 'Janis Joplin', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (194, 'Jeff Beck', 'Jazz');INSERT INTO artist(`index`, artist, genre)
     VALUES (195, 'Jeff Tweedy', 'Folk');INSERT INTO artist(`index`, artist, genre)
     VALUES (196, 'Jefferson Airplane', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (197, 'Jeremy Camp', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (198, 'Jerry Garcia', 'Folk');INSERT INTO artist(`index`, artist, genre)
     VALUES (199, 'Jerry Gonzalez & The Fort Apache Band', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (200, 'Jerry Jeff Walker', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (201, 'Jerry Lee Lewis', 'RockaBilly');INSERT INTO artist(`index`, artist, genre)
     VALUES (202, 'Jesse Cook', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (203, 'Jesse Thomas', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (204, 'Jessi Colter', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (205, 'Jessi Colter & Sunny Sweeney', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (206, 'Jewel', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (207, 'Jim Croce', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (208, 'Jim James & Calexico', 'Folk');INSERT INTO artist(`index`, artist, genre)
     VALUES (209, 'Jimi Hendrix', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (210, 'Jimmy Buffet', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (211, 'Jimmy Witherspoon', 'Jazz');INSERT INTO artist(`index`, artist, genre)
     VALUES (212, 'Joan Baez', 'Folk');INSERT INTO artist(`index`, artist, genre)
     VALUES (213, 'Joe Cocker', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (214, 'Joe Henderson', 'Jazz');INSERT INTO artist(`index`, artist, genre)
     VALUES (215, 'Joe Louis Walker', 'Jazz');INSERT INTO artist(`index`, artist, genre)
     VALUES (216, 'Joe Walsh', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (217, 'John Coltrane', 'Jazz');INSERT INTO artist(`index`, artist, genre)
     VALUES (218, 'John Coltrane & Johnny Hartman', 'Jazz');INSERT INTO artist(`index`, artist, genre)
     VALUES (219, 'John Coltrane and Johnny Hartman', 'Jazz');INSERT INTO artist(`index`, artist, genre)
     VALUES (220, 'John Doe', 'Folk');INSERT INTO artist(`index`, artist, genre)
     VALUES (221, 'John Fahey', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (222, 'John Fahey & His Orchestra', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (223, 'John Hiatt', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (224, 'John Lee Hooker', 'Blues');INSERT INTO artist(`index`, artist, genre)
     VALUES (225, 'John Lennon', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (226, 'John Lennon & The Plastic Ono Band', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (227, 'John Mayall', 'Blues');INSERT INTO artist(`index`, artist, genre)
     VALUES (228, 'John Mayall & The Bluesbreakers', 'Blues');INSERT INTO artist(`index`, artist, genre)
     VALUES (229, 'John Prine', 'Folk');INSERT INTO artist(`index`, artist, genre)
     VALUES (230, 'Johnny Cash', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (231, 'Johnny Mathis', 'Holiday');INSERT INTO artist(`index`, artist, genre)
     VALUES (232, 'Johnny Nash', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (233, 'Johnny Rivers', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (234, 'Johnny Winter', 'Blues');INSERT INTO artist(`index`, artist, genre)
     VALUES (235, 'Jose Luis Encinas', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (236, 'José Feliciano', 'Holiday');INSERT INTO artist(`index`, artist, genre)
     VALUES (237, 'Josh Rouse', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (238, 'Josh Thompson', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (239, 'Journey', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (240, 'Judy Collins', 'Folk');INSERT INTO artist(`index`, artist, genre)
     VALUES (241, 'Julio Iglesias', 'Classic');INSERT INTO artist(`index`, artist, genre)
     VALUES (242, 'Junip', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (243, 'Justin Moore', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (244, 'k.d. lang and the Siss Boom Bang', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (245, 'Kansas', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (246, 'Karen O & The Million Dollar Bashers', 'Folk');INSERT INTO artist(`index`, artist, genre)
     VALUES (247, 'Keith Jarrett', 'Jazz');INSERT INTO artist(`index`, artist, genre)
     VALUES (248, 'Kris Kristofferson', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (249, 'Kris Kristofferson & Patty Griffin', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (250, 'Kris Kristofferson & Rita Coolidge', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (251, 'LaVern Baker', 'Folk');INSERT INTO artist(`index`, artist, genre)
     VALUES (252, 'Led Zeppelin', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (253, 'Leo Kottke', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (254, 'Les McCann', 'Jazz');INSERT INTO artist(`index`, artist, genre)
     VALUES (255, 'Lesley Gore', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (256, 'Less McCann and Eddie Harris', 'Jazz');INSERT INTO artist(`index`, artist, genre)
     VALUES (257, 'Lester Young', 'Jazz');INSERT INTO artist(`index`, artist, genre)
     VALUES (258, 'Linda Ronstadt', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (259, 'Little Dragon', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (260, 'Little Eva', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (261, 'Little Richard', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (262, 'Little River Band', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (263, 'Lloyd Price', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (264, 'Loggins And Messina', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (265, 'Loreena McKennitt', 'Holiday');INSERT INTO artist(`index`, artist, genre)
     VALUES (266, 'Lori McKenna', 'Holiday');INSERT INTO artist(`index`, artist, genre)
     VALUES (267, 'Los Bravos', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (268, 'Los Lobos', 'TexMex');INSERT INTO artist(`index`, artist, genre)
     VALUES (269, 'Lou Reed', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (270, 'Lovin Spoonful', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (271, 'Lynyrd Skynyrd', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (272, 'Madeleine Peyroux', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (273, 'Magokoro Brothers', 'Folk');INSERT INTO artist(`index`, artist, genre)
     VALUES (274, 'Mannheim Steamroller', 'Holiday');INSERT INTO artist(`index`, artist, genre)
     VALUES (275, 'Marcus Carl Franklin', 'Folk');INSERT INTO artist(`index`, artist, genre)
     VALUES (276, 'Mark Knopfler', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (277, 'Mark Knopfler & Emmylou Harris', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (278, 'Mark Knopfler_Emmylou Harris', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (279, 'Mark Lanegan', 'Folk');INSERT INTO artist(`index`, artist, genre)
     VALUES (280, 'Mark Lindsey, Paul Revere & The Raiders', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (281, 'Mark O''Connor', 'Jazz');INSERT INTO artist(`index`, artist, genre)
     VALUES (282, 'Martha Reeves & The Vandellas', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (283, 'Marty Robbins', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (284, 'Marvin Gaye', 'Soul');INSERT INTO artist(`index`, artist, genre)
     VALUES (285, 'Mason Jennings', 'Folk');INSERT INTO artist(`index`, artist, genre)
     VALUES (286, 'Mason Williams', 'Classic');INSERT INTO artist(`index`, artist, genre)
     VALUES (287, 'Matt Nathanson', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (288, 'Mavis Staples', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (289, 'Men At Work', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (290, 'Michael Brecker', 'Jazz');INSERT INTO artist(`index`, artist, genre)
     VALUES (291, 'Michael Martin Murphey', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (292, 'Micheal Brecker', 'Jazz');INSERT INTO artist(`index`, artist, genre)
     VALUES (293, 'Miguel De La Bastide', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (294, 'Miles Band Davis_Sonny Rollins', 'Jazz');INSERT INTO artist(`index`, artist, genre)
     VALUES (295, 'Miles Davis', 'Jazz');INSERT INTO artist(`index`, artist, genre)
     VALUES (296, 'Miles Davis Quintet', 'Jazz');INSERT INTO artist(`index`, artist, genre)
     VALUES (297, 'Miles Davis Sextet_Sonny Rollins', 'Jazz');INSERT INTO artist(`index`, artist, genre)
     VALUES (298, 'Miles Davis_Sonny Rollins', 'Jazz');INSERT INTO artist(`index`, artist, genre)
     VALUES (299, 'Mira Billotte', 'Folk');INSERT INTO artist(`index`, artist, genre)
     VALUES (300, 'Mitch Ryder & The Detroit Wheels', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (301, 'Monsters Of Folk', 'Folk');INSERT INTO artist(`index`, artist, genre)
     VALUES (302, 'Montgomery Gentry', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (303, 'Moody Blues', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (304, 'Mountain Heart', 'BlueGrass');INSERT INTO artist(`index`, artist, genre)
     VALUES (305, 'Muddy Waters', 'Blues');INSERT INTO artist(`index`, artist, genre)
     VALUES (306, 'Mungo Jerry', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (307, 'Nashville Teens', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (308, 'Nat _King_ Cole', 'Holiday');INSERT INTO artist(`index`, artist, genre)
     VALUES (309, 'Neil Sedaka', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (310, 'Neko Case', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (311, 'New Riders of the Purple Sage', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (312, 'Nine Black Alps', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (313, 'Nirvana', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (314, 'Nitty Gritty Dirt Band', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (315, 'Noam Chomsky', 'Talk');INSERT INTO artist(`index`, artist, genre)
     VALUES (316, 'Norah Jones', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (317, 'North Mississippi Allstars', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (318, 'Oliver Kane', 'Classic');INSERT INTO artist(`index`, artist, genre)
     VALUES (319, 'Olivia Newton-John', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (320, 'Oscar Lopez', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (321, 'Oscar Peterson', 'Jazz');INSERT INTO artist(`index`, artist, genre)
     VALUES (322, 'Ottmar Liebert', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (323, 'Ottmar Liebert_Luna Negra', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (324, 'Paco De Lucía', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (325, 'Parts & Labor', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (326, 'Pat Green', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (327, 'Pat Metheny', 'Jazz');INSERT INTO artist(`index`, artist, genre)
     VALUES (328, 'Pat Metheny Group', 'Jazz');INSERT INTO artist(`index`, artist, genre)
     VALUES (329, 'Pat Metheny Trio', 'Jazz');INSERT INTO artist(`index`, artist, genre)
     VALUES (330, 'Patsy Cline', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (331, 'Patti Smith', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (332, 'Paul McCartney & Wings', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (333, 'Paul Simon', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (334, 'Pádraig MacMathúna', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (335, 'Percy Sledge', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (336, 'Pete Seeger & Arlo Guthrie', 'Folk');INSERT INTO artist(`index`, artist, genre)
     VALUES (337, 'Pete Townshend & Ronnie Lane', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (338, 'Peter Bjorn and John', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (339, 'Peter Paul and Mary', 'Folk');INSERT INTO artist(`index`, artist, genre)
     VALUES (340, 'Peter, Paul & Mary', 'Folk');INSERT INTO artist(`index`, artist, genre)
     VALUES (341, 'Philip Selway', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (342, 'Pink Floyd', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (343, 'Playing for Change', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (344, 'Polecat', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (345, 'Prairie Flyer', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (346, 'Prince', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (347, 'Procol Harum', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (348, 'Queen', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (349, 'R.E.M_', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (350, 'R.L. Burnside', 'Blues');INSERT INTO artist(`index`, artist, genre)
     VALUES (351, 'Ramblin'' Jack Elliott', 'Folk');INSERT INTO artist(`index`, artist, genre)
     VALUES (352, 'Randy Houser', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (353, 'Ravel', 'Classic');INSERT INTO artist(`index`, artist, genre)
     VALUES (354, 'Redbird', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (355, 'Reflejo de Luna', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (356, 'Richard Wagner', 'Classic');INSERT INTO artist(`index`, artist, genre)
     VALUES (357, 'Richie Havens', 'Folk');INSERT INTO artist(`index`, artist, genre)
     VALUES (358, 'Ricketic', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (359, 'Ringo Starr', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (360, 'Rita Coolidge', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (361, 'Rita Coolidge & Rupert Holmes', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (362, 'Ritchie Valens', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (363, 'Robert Plant', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (364, 'Robert Plant & Alison Krauss', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (365, 'Roberta Flack', 'Soul');INSERT INTO artist(`index`, artist, genre)
     VALUES (366, 'Roberta Flack & Donny Hathaway', 'Soul');INSERT INTO artist(`index`, artist, genre)
     VALUES (367, 'Rod Stewart', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (368, 'Rodriguez', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (369, 'Roger McGuinn & Calexico', 'Folk');INSERT INTO artist(`index`, artist, genre)
     VALUES (370, 'Roy Buchanan', 'Folk');INSERT INTO artist(`index`, artist, genre)
     VALUES (371, 'Roy Orbison', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (372, 'Ruben Romero', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (373, 'S. Carey', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (374, 'Sam the Sham & The Pharaohs', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (375, 'Santana', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (376, 'Santo And Johnny', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (377, 'Sarah Jarosz', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (378, 'Sarah McLachlan', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (379, 'Savoy Brown', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (380, 'Say Hi', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (381, 'Sertab', 'Folk');INSERT INTO artist(`index`, artist, genre)
     VALUES (382, 'Shirley Caesar', 'Folk');INSERT INTO artist(`index`, artist, genre)
     VALUES (383, 'Shooter Jennings', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (384, 'Simon & Garfunkel', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (385, 'Slash', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (386, 'Small Faces', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (387, 'Sonic Youth', 'Folk');INSERT INTO artist(`index`, artist, genre)
     VALUES (388, 'Sonny & Cher', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (389, 'Sonny Rollins', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (390, 'Sophie Zelmani', 'Folk');INSERT INTO artist(`index`, artist, genre)
     VALUES (391, 'Stanley Turrentine', 'Jazz');INSERT INTO artist(`index`, artist, genre)
     VALUES (392, 'Stealers Wheel', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (393, 'Steely Dan', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (394, 'Stephen Malkmus & Lee Ranaldo', 'Folk');INSERT INTO artist(`index`, artist, genre)
     VALUES (395, 'Stephen Malkmus & The Million Dollar Bashers', 'Folk');INSERT INTO artist(`index`, artist, genre)
     VALUES (396, 'Steppenwolf', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (397, 'Steve Goodman', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (398, 'Steve Miller Band', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (399, 'Stevie Ray Vaughan', 'Blues');INSERT INTO artist(`index`, artist, genre)
     VALUES (400, 'Stevie Ray Vaughan & Double Trouble', 'Blues');INSERT INTO artist(`index`, artist, genre)
     VALUES (401, 'Sting & The Police', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (402, 'Strawberry Alarm Clock', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (403, 'Stray Birds', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (404, 'Stray Cats', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (405, 'Strunz & Farah', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (406, 'Styx', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (407, 'Sufjan Stevens', 'Folk');INSERT INTO artist(`index`, artist, genre)
     VALUES (408, 'T. Rex', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (409, 'Talking Heads', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (410, 'Telekinesis', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (411, 'Ten Years After', 'Blues');INSERT INTO artist(`index`, artist, genre)
     VALUES (412, 'Terry Bozzio, Tony Levin & Steve Stevens', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (413, 'Texas Tornados', 'TexMex');INSERT INTO artist(`index`, artist, genre)
     VALUES (414, 'The Airborne Toxic Event', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (415, 'The Allman Brothers Band', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (416, 'The American Breed', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (417, 'The Animals', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (418, 'The Association', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (419, 'The Band', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (420, 'The Beach Boys', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (421, 'The Beatles', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (422, 'The Beau Brummels', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (423, 'The Belle Brigade', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (424, 'The Black Keys', 'Folk');INSERT INTO artist(`index`, artist, genre)
     VALUES (425, 'The Box Tops', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (426, 'The Buckinghams', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (427, 'The Byrds', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (428, 'The Cars', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (429, 'The Castaways', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (430, 'The Charlie Daniels Band', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (431, 'The Chi-Lites', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (432, 'The Chieftains', 'BlueGrass');INSERT INTO artist(`index`, artist, genre)
     VALUES (433, 'The Coats', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (434, 'The Dave Clark Five', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (435, 'The Diamonds', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (436, 'The Doors', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (437, 'The Drifters', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (438, 'The Eagles', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (439, 'The Electric Prunes', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (440, 'The Everly Brothers', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (441, 'The Five Americans', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (442, 'The Fraternity of Man', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (443, 'The Gentrys', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (444, 'The Grass Roots', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (445, 'The Grateful Dead', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (446, 'The Guess Who', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (447, 'The Handsome Family', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (448, 'The Hold Steady', 'Folk');INSERT INTO artist(`index`, artist, genre)
     VALUES (449, 'The Hollies', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (450, 'The Human Beinz', 'Folk');INSERT INTO artist(`index`, artist, genre)
     VALUES (451, 'The Jazz Crusaders', 'Jazz');INSERT INTO artist(`index`, artist, genre)
     VALUES (452, 'The Kingsmen', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (453, 'The Kingston Trio', 'Folk');INSERT INTO artist(`index`, artist, genre)
     VALUES (454, 'The Kinks', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (455, 'The Knack', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (456, 'The Left Banke', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (457, 'The Mamas & The Papas', 'Folk');INSERT INTO artist(`index`, artist, genre)
     VALUES (458, 'The Marketts', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (459, 'The Marshall Tucker Band', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (460, 'The Mavericks', 'TexMex');INSERT INTO artist(`index`, artist, genre)
     VALUES (461, 'The Outsiders', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (462, 'The Overton Berry Trio', 'Jazz');INSERT INTO artist(`index`, artist, genre)
     VALUES (463, 'The Paul Butterfield Blues Band', 'Blues');INSERT INTO artist(`index`, artist, genre)
     VALUES (464, 'The Pointer Sisters', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (465, 'The Police', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (466, 'The Quintet', 'Jazz');INSERT INTO artist(`index`, artist, genre)
     VALUES (467, 'The Rascals', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (468, 'The Rascals & The Young Rascals', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (469, 'The Righteous Brothers', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (470, 'The Rolling Stones', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (471, 'The Searchers', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (472, 'The Seeds', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (473, 'The Sir Douglas Quintet', 'TexMex');INSERT INTO artist(`index`, artist, genre)
     VALUES (474, 'The Spencer Davis Group', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (475, 'The Surfaris', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (476, 'The Sweet', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (477, 'The Tokens', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (478, 'The Tom Petty_Heartbreakers', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (479, 'The Traveling Wilburys', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (480, 'The Tremeloes', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (481, 'The Troggs', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (482, 'The Turtles', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (483, 'The Ventures', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (484, 'The Wailin'' Jennys', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (485, 'The Who', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (486, 'The Yardbirds', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (487, 'The Young Rascals', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (488, 'The Youngbloods', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (489, 'The Zombies', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (490, 'Thelonious Monk', 'Jazz');INSERT INTO artist(`index`, artist, genre)
     VALUES (491, 'Thelonious Monk Quartet With John Coltrane', 'Jazz');INSERT INTO artist(`index`, artist, genre)
     VALUES (492, 'Them', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (493, 'Three Dog Night', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (494, 'Thunderclap Newman', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (495, 'Tim O''Brien', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (496, 'Tina Turner', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (497, 'Tom Jones', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (498, 'Tom Petty & The Heartbreakers', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (499, 'Tom Verlaine & The Million Dollar Bashers', 'Folk');INSERT INTO artist(`index`, artist, genre)
     VALUES (500, 'Tony Bennett', 'Holiday');INSERT INTO artist(`index`, artist, genre)
     VALUES (501, 'Tony Burgos & His Swing Shift Orchestra', 'Jazz');INSERT INTO artist(`index`, artist, genre)
     VALUES (502, 'Toto', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (503, 'Tower of Power', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (504, 'Trace Adkins', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (505, 'Traffic', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (506, 'U2', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (507, 'Uncle Earl', 'BlueGrass');INSERT INTO artist(`index`, artist, genre)
     VALUES (508, 'Union Gap', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (509, 'Unknown Artist', 'BlueGrass');INSERT INTO artist(`index`, artist, genre)
     VALUES (510, 'Van Morrison', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (511, 'Wagner', 'Classic');INSERT INTO artist(`index`, artist, genre)
     VALUES (512, 'Walela', 'Folk');INSERT INTO artist(`index`, artist, genre)
     VALUES (513, 'Walt Weiskopf Nonet', 'Jazz');INSERT INTO artist(`index`, artist, genre)
     VALUES (514, 'War', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (515, 'Waylon and Willie', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (516, 'Waylon Jennings', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (517, 'Waylon Jennings & The Waylors', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (518, 'Waylon Jennings & Willie Nelson', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (519, 'Wayne Fontana & The Mindbenders', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (520, 'We Are Augustines', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (521, 'Weather Report', 'Jazz');INSERT INTO artist(`index`, artist, genre)
     VALUES (522, 'White Lion', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (523, 'Wilbert Harrison', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (524, 'Willie Nelson & Calexico', 'Folk');INSERT INTO artist(`index`, artist, genre)
     VALUES (525, 'Willie Nelson and Leon Russel', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (526, 'Wings', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (527, 'Wrabel', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (528, 'Wyatt McCubbin', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (529, 'Wye Oak', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (530, 'Wynton Marsalis & Eric Clapton', 'Jazz');INSERT INTO artist(`index`, artist, genre)
     VALUES (531, 'Yes', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (532, 'Yo La Tengo', 'Folk');INSERT INTO artist(`index`, artist, genre)
     VALUES (533, 'Yo-Yo Ma', 'Pop');INSERT INTO artist(`index`, artist, genre)
     VALUES (534, 'Zac Brown Band', 'Country');INSERT INTO artist(`index`, artist, genre)
     VALUES (535, 'ZZ Top', 'Rock');INSERT INTO artist(`index`, artist, genre)
     VALUES (536, 'ZTest', 'Test');COMMIT;